version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      all-updates:
        exclude-patterns:
          - "kube"
          - "k8s-openapi"
      kube-updates:
        patterns:
          - "kube"
          - "k8s-openapi"
